# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb23ce57812f21c026affaf69dffa79eb227f979003ffc6d27b70e74667e48c1401b89625c6ffebd3e61c98b0106c2b87c456dadd8847d4f4bc02290ce9c5bf7

test:
  secret_key_base: 0aebb8486c22246a67709be932e564d309ef3c2df10411030c75757cc224c72d4c25802e854c3f712b0bcd89858b68dc17ea71f7c1ed4644182290ff2ee8dfcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
